### ISSUE TITLE
h2oGPT stability issues: no reply after a few successful Q & A

### ISSUE THREAD

**Issue by hpxiong** [h2oai/h2ogpt#1100] opened 2023-11-16 04:29 UTC
I'm not sure what's causing the issue, and there's not much error message I can find. After a few successful chat questions, the backend becomes stuck and is unable to process requests, resulting in no reply. 

I uploaded a collection of about 20 documents to the backend, and they are all small with no more than 1 MB each. However, after having a few successes in Q&A, the backend became stuck and is reproducibly stuck on my system every time.

Some other related problems are:

1. Even when document subset "Relevant" is selected, the answer tends to only include top few documents. I have to correct and reinforce the model a few times to iterate more documents. 

2. when multiple users are accessing h2oGPT at the same time, almost all the time, the system will stuck and run into some kind of locking state and not able to recover.

I'm running from a Windows server with 128GB memory and A100 GPU. I have similar stability issues on an Ubuntu with 16GB memory + Titan X GPU. 
 
 I used below command to start the app.

```cmd
python generate.py  
	--base_model='llama'              
        --model_path_llama=D:/model/llama-2-7b-chat.Q6_K.gguf
	--prompt_type=llama2 
	--score_model=None 
	--langchain_mode='UserData' 
	--user_path=user_path                 
	--max_seq_len=4096 
	--llamacpp_dict={'n_gpu_layers':35,'n_batch':128} ,
	--share=False                 
	--verbose=True
	--gradio_offline_level=2
	--debug=True				
```

example of the messages when it hung

```cmd
llama_print_timings:        load time =  4144.86 ms
llama_print_timings:      sample time =   189.62 ms /   792 runs   (    0.24 ms per token,  4176.77 tokens per second)
llama_print_timings: prompt eval time =  2816.06 ms /  2725 tokens (    1.03 ms per token,   967.66 tokens per second)
llama_print_timings:        eval time = 13985.81 ms /   791 runs   (   17.68 ms per token,    56.56 tokens per second)
llama_print_timings:       total time = 19944.69 ms

> Finished chain.

> Finished chain.
\miniconda3\envs\h2ogpt\lib\site-packages\gradio\helpers.py:818: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Textbox(...)` instead of `return gr.update(...)
  warnings.warn(
\miniconda3\envs\h2ogpt\lib\site-packages\gradio\components\radio.py:134: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Radio(...)` instead of `return gr.Radio.update(...)`.
  warnings.warn(
```

**Comment by pseudotensor** [comment] 2023-11-18 02:14
Hi.  I'm so far unable to reproduce.  Perhaps the version of llama_cpp_python you are using is bad, and you can use a new version.  I noticed version 0.14 was bad, and recently moved to 0.18 that seems ok apart from some issues being able to run CPU and GPU at same time (which is being fixed by them and others).

My version of your command, which had some typos (beyond path changes):

```
python generate.py --base_model=llama     --model_path_llama=llama-2-7b-chat.Q6_K.gguf --prompt_type=llama2  --score_model=None  --langchain_mode=UserData --user_path=user_path         --max_seq_len=4096  --llamacpp_dict="{'n_gpu_layers':35,'n_batch':128}" --share=False                  --verbose=True --gradio_offline_level=2 --debug=True
```


```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ pip freeze | grep llama
exllama @ https://github.com/jllllll/exllama/releases/download/0.0.13/exllama-0.0.13+cu118-cp310-cp310-linux_x86_64.whl#sha256=18bf2ed94860c350713889f4b2793189f0615eb95a5a9a1ae64b3e2a993021bb
llama-hub==0.0.43
llama-index==0.8.65
llama_cpp_python==0.2.18+cu118
llama_cpp_python_cuda @ https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.18+cu118-cp310-cp310-manylinux_2_31_x86_64.whl#sha256=1dfc80552277a8e22be3b115f5afd467f846ff12511fa9af14bd2f5392f15f90

```

![image](https://github.com/h2oai/h2ogpt/assets/2249614/1fac254b-50b6-4944-b700-4ff4175c4c1a)

**Comment by hpxiong** [comment] 2023-11-20 01:33
> Hi. I'm so far unable to reproduce. Perhaps the version of llama_cpp_python you are using is bad, and you can use a new version. I noticed version 0.14 was bad, and recently moved to 0.18 that seems ok apart from some issues being able to run CPU and GPU at same time (which is being fixed by them and others).
> 
> My version of your command, which had some typos (beyond path changes):
> 
> ```
> python generate.py --base_model=llama     --model_path_llama=llama-2-7b-chat.Q6_K.gguf --prompt_type=llama2  --score_model=None  --langchain_mode=UserData --user_path=user_path         --max_seq_len=4096  --llamacpp_dict="{'n_gpu_layers':35,'n_batch':128}" --share=False                  --verbose=True --gradio_offline_level=2 --debug=True
> ```
> 
> ```
> (h2ogpt) jon@pseudotensor:~/h2ogpt$ pip freeze | grep llama
> exllama @ https://github.com/jllllll/exllama/releases/download/0.0.13/exllama-0.0.13+cu118-cp310-cp310-linux_x86_64.whl#sha256=18bf2ed94860c350713889f4b2793189f0615eb95a5a9a1ae64b3e2a993021bb
> llama-hub==0.0.43
> llama-index==0.8.65
> llama_cpp_python==0.2.18+cu118
> llama_cpp_python_cuda @ https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.2.18+cu118-cp310-cp310-manylinux_2_31_x86_64.whl#sha256=1dfc80552277a8e22be3b115f5afd467f846ff12511fa9af14bd2f5392f15f90
> ```
> 
> ![image](https://user-images.githubusercontent.com/2249614/283966992-1fac254b-50b6-4944-b700-4ff4175c4c1a.png)

I will try your suggestions and update here. thx.

**Comment by hpxiong** [comment] 2023-11-28 05:47
I did some testing on the system provided here and the RAG results appear to be poor as well. 

In the example below, I uploaded 6 pdf files which contain randomly generated name, address, etc. information. All the 4 models cannot traverse all the files and provide correct answers. Correct answer should be 6 unique addresses. 

Also, as you can see, the GPT-3.5-turbo model window is frozen, and no result is returned. The whole web UI is not responsive to new query anymore. 

![image](https://github.com/h2oai/h2ogpt/assets/17347604/4990a0cb-9497-4b5a-a9da-741fd9d13d66)

If you are interested, here is my script that generates pdf files for testing. 
https://gist.github.com/hpxiong/c962c3165b6edb5266198162caf7f92f

**Comment by pseudotensor** [comment] 2023-12-10 03:46
Hi, poor results in some cases are an ever-expanding part of improvements in RAG in the entire field.

**Comment by hpxiong** [comment] 2023-12-11 06:30
> Hi, poor results in some cases are an ever-expanding part of improvements in RAG in the entire field.

That is fair. I do see improvements in results when tweaking the data format and prompts. 

My main concern with h2oGPT experience above is that it can sometimes become unresponsive, causing confusion and frustration for users who are unsure of what's happening.

**Comment by pseudotensor** [comment] 2023-12-11 09:19
Understood.  I haven't seen that, as we discussed at first.  I am not sure what is happening.

**Comment by hpxiong** [comment] 2023-12-13 00:07
> Understood. I haven't seen that, as we discussed at first. I am not sure what is happening.

I'm surprised that you haven't seen that. I ran into system not responding all the time, even with the demo sites listed here.

**Comment by pseudotensor** [comment] 2023-12-13 00:14
I was referring to the empty response.

As for poor responsiveness, we have been noticing lately and went through a round of stress testing.  I believe main is now much better and won't do that.  You shouldn't see gpt.h2o.ai do anything non-responsive either.  Let me know.

**Comment by pseudotensor** [comment] 2024-03-14 21:12
Try latest h2oGPT with latest llama.cpp inside. jaiss is just bad model roughly.

**Closed by pseudotensor** 2024-03-14 21:12 UTC
