### ISSUE TITLE
Incorrect response and mentioned wrong source when querying from UserData

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2ogpt#1121] opened 2023-11-22 09:18 UTC
When i hit the following command
 `python generate.py --inference_server="vllm:0.0.0.0:5000" --base_model=meta-llama/Llama-2-13b-chat-hf  --score_model=None --langchain_mode='UserData' --user_path=user_path --use_auth_token=True --max_seq_len=4096 --max_max_new_tokens=2048 --max_batch_size=16 --concurrency_count=64`
 and asking the query from **UserData**
 then it start generating response other than **UserData** and also given the **source** which are not related at all.

For example: my userdata have a source documents related to principles of aircrafs but when I asking the query like "How to cook a biryani with paneer" then it generating responses for cook a biryani that are not related to the userdata and also show the sources that are not relating the cook a biryani

So i just want when userdata is selected and someone asking the question other than userdata like mentioned above then it should response like "there are no mention of how to cook birayni in the documents and also not showing the source for that query. 

For more reference please check the attached screenshot.
![h2ogpt](https://github.com/h2oai/h2ogpt/assets/137979399/36cc9892-351d-41dd-bdd2-6645e0bfbcd4)

**Comment by llmwesee** [comment] 2023-12-07 03:47
Please @pseudotensor look into this issue. I pull the latest repo and still facing the same issue.

**Comment by pseudotensor** [comment] 2023-12-07 04:05
Hi, others had a related issue that is already fixed as they confirmed.

https://github.com/h2oai/h2ogpt/issues/1142

However, I don't have enough information to investigate your issue.  If you can formula a reproducible example to some extent I can look.

It's unlikely that when choosing UserData it's pulling from MyData etc.  I don't see enough information in the snapshot to see that is confirmed.  E.g. you could show that those files are not present in the document selection in UserData and only present in  MyData.

As for incorrect response etc.  Your document headers seem to have odd characters, as if the PDF was not parsed correctly.  Perhaps confirm that they were parsed correctly.  Maybe it's just making up information, while you think it's coming from another database.  Again, I can't see any evidence of the data coming from another database.

**Comment by llmwesee** [comment] 2023-12-07 09:25
For example think this scenario:
I uploaded 3 pdfs related to coding questions in userdata. Now I select userdata in collection and ask query like "how to make pizza" then it start generating responses for "how to make pizza" but my userdata have information related to coding questions.

So I simply want if LLM doesn't find query relevent to the content of userdata then it simply says like "I didn't find any information related to the query in user data" and just not making up information own its own. Also not showing the sources if the query isn't relevent to the userdata.

**Comment by pseudotensor** [comment] 2023-12-09 09:16
Hi @llmwesee You can add `--use_llm_if_no_docs=False` and tune the `--cut_distance=1.64` to a smaller value in order to be stricter about what is allowed.

Every user is different.  At some point I had use_llm_if_no_docs False by default, but others didn't like that.

Also, if you use bge or other embedding models, that cut_distance needs to be tuned anyways.

**Comment by pseudotensor** [comment] 2023-12-09 09:18
I'm going to close this in favor of the other feature issue with that auto-thresholding, since I think there is no specific bug.

https://github.com/h2oai/h2ogpt/issues/1095

**Closed by pseudotensor** 2023-12-09 09:18 UTC
