### ISSUE TITLE
Answered: How use GGUF model on h2oGPT  for CPU

### ISSUE THREAD

**Issue by bluciano212** [h2oai/h2ogpt#904] opened 2023-09-27 21:21 UTC
Hi , I have found these 2, 3, 4, 5, 6 and 8-bit GGUF models for CPU :
https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF
How can I use this llama-2-7b-chat.Q4_K_M.gguf on h2oGPT for CPU ?

Previously for GGML moldel I wrote :
python3 generate.py --base_model='llama' --model_path_llama=llama-2-7b-chat.ggmlv3.q4_1.bin --max_seq_len=2048 --prompt_type=llama2 --score_model=None --langchain_mode='UserData'

Now if I write :
python3 generate.py --base_model='llama' --model_path_llama=llama-2-7b-chat.Q4_K_M.gguf --max_seq_len=2048 --prompt_type=llama2 --score_model=None --langchain_mode='UserData'
obviously it does not work .
Any suggestion please?

**Comment by juerware** [comment] 2023-10-02 09:00
Hi, I am trying to use GGUF as well with the following command line:
python generate.py \
    --base_model="TheBloke/Mistral-7B-v0.1-GGUF" \
    --prompt_type=llama2 \
    --use_gpu_id=True \
    --gpu_id=-1 \
    --max_seq_len=4096 \
    --user_path=/opt/myDocuments/ \
    --langchain_mode='UserData' \
    --max_quality=True \
    --add_chat_history_to_context=True \
    --keep_sources_in_context=True \
    --enable_ocr=True \
    --enable_doctr=True \
    --hf_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" \
    --append_sources_to_answer=True \
    --answer_with_sources=True \
    --show_link_in_sources=True \
    --memory_restriction_level=0 \
    --score_model='' \
    --verbose=True;

And I get the following error:
Traceback (most recent call last):
  File "/opt/void_h2ogtp/generate.py", line 16, in <module>
    entrypoint_main()
  File "/opt/void_h2ogtp/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/opt/void_h2ogtp/src/utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/void_h2ogtp/src/gen.py", line 1189, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "/opt/void_h2ogtp/src/gen.py", line 1563, in get_model
    config, _, max_seq_len = get_config(base_model, **config_kwargs, raise_exception=False)
  File "/opt/void_h2ogtp/src/gen.py", line 1278, in get_config
    config = AutoConfig.from_pretrained(base_model, use_auth_token=use_auth_token,
  File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1039, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 734, in __getitem__
    raise KeyError(key)
KeyError: 'mistral'

There is a little piece of information about GGUF in repository documentation:
https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md
in the section: GPU Optional: Support LLaMa.cpp with CUDA
# GGUF ONLY:
pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-linux_x86_64.whl

I followed the documentation but it failed.
if someone can help me, thanks in advance.

**Comment by bluciano212** [comment] 2023-10-02 20:51
Hi ,what kind of hardware do you have?Are you using CPU only or GPU?
I think before you have to unistall as following
pip uninstall llama_cpp_python_cuda 
pip uninstall llama_cpp_python

**Comment by juerware** [comment] 2023-10-03 06:44
Distribution: "Ubuntu 22.04.3 LTS" completely updated.

Every model is trying to be use with GPU

$ pip list | grep -iP '(llama|cuda)'
llama-cpp-python-cuda        0.1.83+cu117 # this is the version installed in the machine

Last commit in github repository is applied:
* 7fbe6659 Jonathan C. McKinney (HEAD -> main, origin/main, origin/HEAD) (Mon, 2 Oct 2023 23:30:06 -0700) [Fix defaults]
* 1c93f1c2 Jonathan C. McKinney (Mon, 2 Oct 2023 22:56:35 -0700) [Minor fixes to readme]
* 88fee487 Chathrinda Ranasinghe (Tue, 3 Oct 2023 10:37:38 +0530) [ci: Build wheel after modifying version (#921)]
.......

I would like to try exactly model "TheBloke/Mistral-7B-v0.1-GGUF" in the following way:
$ python generate.py
--base_model=**"TheBloke/Mistral-7B-v0.1-GGUF"**
--prompt_type=llama2
--use_gpu_id=True
--gpu_id=-1
--max_seq_len=4096
--user_path=/opt/myDocuments/
--langchain_mode='UserData'
--max_quality=True
--add_chat_history_to_context=True
--keep_sources_in_context=True
--enable_ocr=True
--enable_doctr=True
--hf_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
--append_sources_to_answer=True
--answer_with_sources=True
--show_link_in_sources=True
--memory_restriction_level=0
--score_model=''
--verbose=True;

With other models I have not found any problem and they execute seamlessly.
if someone can help me, thanks.

**Comment by juerware** [comment] 2023-10-05 11:28
At the end It works, not fast as I hoped but It is working right now with gguf models:

python generate.py \
    --base_model='llama' --prompt_type=llama2 --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q8_0.gguf --use_gpu_id=True --gpu_id=-1 --max_seq_len=4096 \
    --user_path=/opt/myDocuments/ --langchain_mode='UserData' --max_quality=True \
    --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True \
    --hf_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" --append_sources_to_answer=True --answer_with_sources=True --show_link_in_sources=True \
    --show_examples=True \
    --memory_restriction_level=0 \
    --score_model='' \
    --verbose=True \
    --share=True

**Comment by pseudotensor** [comment] 2023-10-06 00:36
@juerware Perhaps confirm how much the GPU is offloaded if using GPUs.

**Comment by juerware** [comment] 2023-10-06 08:36
Hi, I will show statistic for one execution.

Device 0 [NVIDIA A30] PCIe GEN 4@16x RX: 293.9 MiB/s TX: 118.2 MiB/s Device 1 [NVIDIA A30] PCIe GEN 4@16x RX: 79.10 MiB/s TX: 124.0 MiB/s
GPU 1440MHz MEM 1215MHz TEMP  33fC FAN N/A% POW  79 / 165 W          GPU 930MHz  MEM 1215MHz TEMP  31fC FAN N/A% POW  52 / 165 W
GPU[||||||||||||              42%] MEM[|||||||||   7.821Gi/24.000Gi] GPU[|||||||||||               38%] MEM[|||||       4.320Gi/24.000Gi]

llama_print_timings:        load time =   204.51 ms
llama_print_timings:      sample time =   461.67 ms /   863 runs   (    0.53 ms per token,  1869.31 tokens per second)
llama_print_timings: prompt eval time =   204.43 ms /    24 tokens (    8.52 ms per token,   117.40 tokens per second)
llama_print_timings:        eval time = 21491.15 ms /   862 runs   (   24.93 ms per token,    40.11 tokens per second)
llama_print_timings:       total time = 24151.51 ms

As it can be watched the parameters used has been:
--use_gpu_id=True # to force using GPU
--gpu_id=-1 # to force using all GPUs available in the system
So that, using GPU and using all GPUs

The problem falls when these parameters are used:
--use_gpu_id=True # to force using GPU
--gpu_id=0 # to force using only GPU device 0 (the first one)
Or this another one:
--use_gpu_id=False # to force using CPU
In these 2 last "use cases" the "software" h2oGPT always uses GPU and all GPUs (devices) available in the system therefore, It do not work properly.
The repository is up to date.

I hope this information was usefull.
If you need something else, please, let me know, thanks in advance.

**Comment by pseudotensor** [comment] 2023-10-07 03:43
Right, for llama I'm not aware of mechanism to control which or how many GPUs are used except externally via CUDA_VISIBLE_DEVICES environment variable.  I'll take a look again at this.

**Comment by pseudotensor** [comment] 2023-10-07 03:47
Seems llama python cpp and llama.cpp itself do not support selecting which GPU.  has to be done via that env I mentioned: https://github.com/abetlen/llama-cpp-python/issues/290

**Comment by zz2115** [comment] 2023-10-08 16:15
> Hi, I am trying to use GGUF as well with the following command line: python generate.py --base_model="TheBloke/Mistral-7B-v0.1-GGUF" --prompt_type=llama2 --use_gpu_id=True --gpu_id=-1 --max_seq_len=4096 --user_path=/opt/myDocuments/ --langchain_mode='UserData' --max_quality=True --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True --hf_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" --append_sources_to_answer=True --answer_with_sources=True --show_link_in_sources=True --memory_restriction_level=0 --score_model='' --verbose=True;
> 
> And I get the following error: Traceback (most recent call last): File "/opt/void_h2ogtp/generate.py", line 16, in entrypoint_main() File "/opt/void_h2ogtp/generate.py", line 12, in entrypoint_main H2O_Fire(main) File "/opt/void_h2ogtp/src/utils.py", line 64, in H2O_Fire fire.Fire(component=component, command=args) File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire component_trace = _Fire(component, args, parsed_flag_args, context, name) File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire component, remaining_args = _CallAndUpdateTrace( File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace component = fn(*varargs, **kwargs) File "/opt/void_h2ogtp/src/gen.py", line 1189, in main model0, tokenizer0, device = get_model(reward_type=False, File "/opt/void_h2ogtp/src/gen.py", line 1563, in get_model config, _, max_seq_len = get_config(base_model, **config_kwargs, raise_exception=False) File "/opt/void_h2ogtp/src/gen.py", line 1278, in get_config config = AutoConfig.from_pretrained(base_model, use_auth_token=use_auth_token, File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1039, in from_pretrained config_class = CONFIG_MAPPING[config_dict["model_type"]] File "/opt/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 734, in **getitem** raise KeyError(key) KeyError: 'mistral'
> 
> There is a little piece of information about GGUF in repository documentation: https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md in the section: GPU Optional: Support LLaMa.cpp with CUDA GGUF ONLY: pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-linux_x86_64.whl
> 
> I followed the documentation but it failed. if someone can help me, thanks in advance.

you shared your success with Llama-2-7b-Chat; did you get mistral 7b insturct working eventually?

**Comment by pseudotensor** [comment] 2023-10-09 03:14
Mistral 7b instruct support was merged.  need new transformers as changed in the requirements file.

**Comment by bluciano212** [comment] 2023-10-11 21:28
Hi , finally after several trials I have loaded GGUF model on h2o localGPT "CPU only" for **SBC arm64 orange pi 5**  . I have removed previous h2oGPT installation and installed latest (10/10/2023)
git clone https://github.com/h2oai/h2ogpt.git 
cd h2ogpt
pip install -r requirements.txt
pip install -r reqs_optional/requirements_optional_langchain.txt
pip install -r reqs_optional/requirements_optional_gpt4all.txt
pip install -r requirements.txt --extra-index https://download.pytorch.org/whl/cpu
(after receive message:gpt4all 0.1.7 requires pytest==7.3.1, but you have pytest 7.2.2 which is incompatible)
pip install pytest==7.3.1
pip install chromadb-0.4.13
pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt
pip install -r reqs_optional/requirements_optional_langchain.urls.txt
sudo apt-get install -y libmagic-dev poppler-utils tesseract-ocr libtesseract-dev libreoffice
(finally for GGUF model) 
**pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir**

it result in :
Successfully uninstalled llama-cpp-python-0.1.77
Successfully installed diskcache-5.6.3 llama-cpp-python-0.2.11 numpy-1.26.0 typing-extensions-4.8.0

run:
ulimit -l unlimited && python3 generate.py --base_model='llama' --model_path_llama=llama-2-7b-chat.Q4_K_M.gguf --max_seq_len=2048 --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=/home/lucio/book

I have some warnings, but it works fine (see txt file), it is stable and gives correct replies.Pdf ingestion is faster than previous (13/8/2023). Ram usage rise from 900Mb to 6.6Gb . I will try to  install h2oGPT also on raspberry 4 8Gb

[h2oGPT GGUF.txt](https://github.com/h2oai/h2ogpt/files/12874503/h2oGPT.GGUF.txt)

I see at starting  GGUF model load tensors,  NPU in the Rockchip RK3588S of Orange pi5 would handle those tensors better than CPU . I have found librknnrt.so: is a RK3588S board-side runtime library for NPU .
but I do not know how pip install can include it during h2oGPT installation. If someone else is using Orange pi 5 or similar SBC with NPU please reply 

![Screenshot (8)](https://github.com/h2oai/h2ogpt/assets/142985563/7fb7aefa-ae82-46ef-9759-357dd9541bc4)

**Comment by pseudotensor** [comment] 2023-10-13 22:07
Thanks for detailed instructions.  If there is something you think could be added to docs, please make a PR if that's ok. Thanks!

**Comment by bluciano212** [comment] 2023-10-18 21:31
hi, sure I have understand during trial and errors, how to install h2o localGPT on SingleBoardComputer , It's not fast as GPU , but it works, If you want to add a section in docs about h2o localGPT setup on SBC  I can write the procedure I followed. 
Maybe it can be useful for schools that normally use SBC like raspeberry and use it to learn how AI model works. 

Concerning **mistral** model
I have read you replied to an user : **As for the 7B llama-2, it's not great with documents. I recommend mistral 7b instead if using 7b**
So I downloaded "mistral-7b-v0.1.Q4_K_M.gguf" for CPU
and run  as following :
ulimit -l unlimited && python3 generate.py --base_model='llama' --model_path_llama=mistral-7b-v0.1.Q4_K_M.gguf --max_seq_len=2048 --prompt_type=llama2 --score_model=None --add_chat_history_to_context=True --langchain_mode='UserData' --user_path=/home/lucio/book 

I 'm not sure it is the right syntax, I do not see any error , but neither any reply to my query

**Comment by pseudotensor** [comment] 2023-10-19 07:50
@bluciano212 For mistral you cannot use llama2 prompt_type.   You should use `--prompt_type=mistral`

**Comment by juerware** [comment] 2023-10-19 10:29
I have done the following proof with mistral:

```
python generate.py \
    --base_model='llama' \
    --prompt_type=mistral \
    --model_path_llama=https://huggingface.co/TheBloke/Mistral-7B-v0.1-GGUF/resolve/main/mistral-7b-v0.1.Q8_0.gguf \
    --use_gpu_id=True \
    --gpu_id=-1 \
    --max_seq_len=4096 \
    --user_path=/opt/myDocuments/ \
    --langchain_mode='UserData' \
    --max_quality=True \
    --add_chat_history_to_context=True \
    --keep_sources_in_context=True \
    --enable_ocr=True \
    --enable_doctr=True \
    --hf_embedding_model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" \
    --append_sources_to_answer=True \
    --answer_with_sources=True \
    --show_link_in_sources=True \
    --memory_restriction_level=0 \
    --score_model=None \
    --verbose=True \
    --share=True \
```
And It is working right BUT the problem is in UI getting the error:
![image](https://github.com/h2oai/h2ogpt/assets/62417778/288e13a4-d142-43e7-a7e0-72800e9f5dfa)

UI is not able to catch the response from backend.

In backend execution the response for verbose is:
```
llama_print_timings:        load time =   187.63 ms
llama_print_timings:      sample time =  2022.22 ms /  3450 runs   (    0.59 ms per token,  1706.04 tokens per second)
llama_print_timings: prompt eval time =   187.56 ms /    16 tokens (   11.72 ms per token,    85.30 tokens per second)
llama_print_timings:        eval time = 99852.31 ms /  3449 runs   (   28.95 ms per token,    34.54 tokens per second)
llama_print_timings:       total time = 116587.60 ms
```
It seems it is working right.

**Comment by bluciano212** [comment] 2023-10-19 21:02
hi thanks, now  I wrote:
ulimit -l unlimited && python3 generate.py --base_model='llama' --prompt_type=mistral --model_path_llama=mistral-7b-v0.1.Q4_K_M.gguf --max_seq_len=4096 --prompt_type=llama2 --score_model=None --add_chat_history_to_context=True --langchain_mode='UserData' --user_path=/home/lucio/book

but the UI does not write any answer to my question, UI now shows only the source link 

@juerware are you having same issue ? UI with mistral model does not show any reply even to you?

**Comment by pseudotensor** [comment] 2023-10-19 21:06
You have --prompt_type listed twice.  Please only use the correct one.

**Comment by pseudotensor** [comment] 2023-10-19 21:11
i.e. for GGUF (not default in h2oGPT and currently not selectable separately from GGML) do:
```
pip uninstall -y llama-cpp-python llama-cpp-python-cuda
pip install https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases/download/textgen-webui/llama_cpp_python_cuda-0.1.83+cu117-cp310-cp310-linux_x86_64.whl
python generate.py --base_model=llama --prompt_type=mistral --model_path_llama=https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf --max_seq_len=4096 --score_model=None
```

to get:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/6c6b9330-5a9e-477d-9101-1bed3fff3bae)


It's very fast on my 3090ti GPU.

**Closed** 2023-10-19 21:35 UTC
Labels: type/question

**Comment by bluciano212** [comment] 2023-10-22 17:48
thank you very much for the suggestion ,now it works perfectly , no more confusion or python error!
ulimit -l unlimited && python3 generate.py --base_model='llama' --model_path_llama=mistral-7b-instruct-v0.1.Q4_K_M.gguf --max_seq_len=4096 --prompt_type=mistral --score_model=None --add_chat_history_to_context=True --langchain_mode='UserData' --user_path=/home/lucio/book
