### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by patrickhwood** [h2oai/h2ogpt#669] opened 2023-08-14 23:33 UTC
A few documentation additions would be useful:

1. How to use make_db.py with docker, e.g., it fails without --save_dir.
2. Need to also mount -v "${HOME}"/.cache:/root/.cache for the instructor-large model to be saved properly (or set TORCH_HOME in the Dockerfile).
3. docker runs the container as root and fails with --user=<my uid>
4. The database is stored in the local directory, so either db_dir_<db-name> should be mounted to /workspace or $PWD at the head of the git repo should be mounted *as* /workspace.  (This second option should be mentioned as a good way to debug the docker container and even perform development.)

**Comment by achraf-mer** [comment] 2023-08-22 14:31
Thanks for the feedback @patrickhwood, my comments inlined:

>1. How to use make_db.py with docker, e.g., it fails without --save_dir.

@pseudotensor any idea about above?

>2. Need to also mount -v "${HOME}"/.cache:/root/.cache for the instructor-large model to be saved properly (or set TORCH_HOME in the Dockerfile).

should be covered by https://github.com/h2oai/h2ogpt/pull/728.

>4. docker runs the container as root and fails with --user=

the default docker user is `h2ogpt` not root, can you please point out how you ran the container to get it in a failed state?

>5. The database is stored in the local directory, so either db_dir_ should be mounted to /workspace or $PWD at the head of the git repo should be mounted as /workspace. (This second option should be mentioned as a good way to debug the docker container and even perform development.)

we do recommend to mount this directory `-v "${HOME}"/save:/workspace/save` as per description here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md, this can be used for all the save operations to maintain files locally, @pseudotensor are you aware of any other files that we automatically save with no option to specify the target location? (meaning things that we could lose if we terminate the container)

**Comment by pseudotensor** [comment] 2023-08-22 16:44
@achraf-mer On this one:
```
How to use make_db.py with docker, e.g., it fails without --save_dir.
```
make_db doesn't use --save_dir.


However, I think the issue is being able to run not just generate.py but also src/make_db.py since that is a separate thing one can run.  Is that possible?  Can we document?

**Comment by patrickhwood** [comment] 2023-08-22 21:10
Sorry.  I mean --user_path.  And yes, the issue is running make_db.py with docker, since the main reason I'm using docker is to have a separate python environment for all h2ogpt operations, since I didn't bother with requirements.txt in order to run generate.py with docker.

This was more a request to expand the docker docs, than a problem report running the code.

src/make_db.py runs fine with docker if I mount the directory with the DB inputs into the docker file system and use --user_path.

**Comment by patrickhwood** [comment] 2023-08-22 21:22
> the default docker user is h2ogpt not root, can you please point out how you ran the container to get it in a failed state?

Running your docker image with  -u `id -u`:`id -g` fails:

```
$ docker run --rm --init -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -u `id -u`:`id -g` gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0
[FATAL tini (6)] exec python3.10 failed: Permission denied
$ uname -a
Linux pat4090 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
```
Runs fine as root:

```
docker run -it --rm gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by patrickhwood** [comment] 2023-08-22 21:38
> Thanks for the feedback @patrickhwood, my comments inlined:
> 
> > 5. The database is stored in the local directory, so either db_dir_ should be mounted to /workspace or $PWD at the head of the git repo should be mounted as /workspace. (This second option should be mentioned as a good way to debug the docker container and even perform development.)
> 
> we do recommend to mount this directory `-v "${HOME}"/save:/workspace/save` as per description here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_DOCKER.md, this can be used for all the save operations to maintain files locally, @pseudotensor are you aware of any other files that we automatically save with no option to specify the target location? (meaning things that we could lose if we terminate the container)

Fair enough, but by default the database goes into a file in the docker current directory named db_dir_...  That's not mounted in your examples, and the examples don't attempt to put the db_dir in some place that's permanent.  I'm sure this is all documented in great detail somewhere in the massive trove of readmes you have, but for the docker-specific readme, you should at least try to show how to set things up to be permanent across docker runs.

**Comment by patrickhwood** [comment] 2023-08-22 21:46
For me, running the docker image was easier by simply making a directory specifically for h2ogpt and running docker inside it with:
```
mkdir -p ~/h2o/save
-v "${HOME}"/h2o:/workspace
```
Instead of

`-v "${HOME}"/save:/workspace/save`

which captures all the locally-created files.

**Comment by achraf-mer** [comment] 2023-08-24 21:42
```
$ docker run --rm --init -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -u `id -u`:`id -g` gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 --version
Python 3.10.9
```
with latest image to date with a non root user: `sha256:1934c3ec44b2e2496cb6b08f8e02ed1257a417aac8d395e57ab8aa656ad72459`

Added readme doc here: https://github.com/h2oai/h2ogpt/pull/750, PTAL, thanks.

**Comment by achraf-mer** [comment] 2023-08-25 15:03
Documentation updated to fix running the `src/make_db.py` script from docker and to show case the directories that can be mounted into the container.
Closing, but please feel free to re-open if further improvements are needed, thanks.

**Closed by achraf-mer** 2023-08-25 15:03 UTC
