### ISSUE TITLE
GGML_ ASSERT: /private/var/folders/g0/p18kgc7d571crl09kq2j1hpm0000gp/T/pip-install-mmgwywty/llama-cpp-python_7e131ef142c044a6a72760eb49448fe4/ven  dor/llama.cpp/ggml-backend.c:212: offset + size <= ggml_nbytes(tensor) && "tensor read out of bounds"  Fatal Python error: Aborted

### ISSUE THREAD

**Issue by SkanderBS23** [h2oai/h2ogpt#1450] opened 2024-03-05 03:04 UTC
Hello,

After using for couple of minutes, this error occurs and the client gets disconnected. Is there any solution that resolves the issue ?
Getting this error with the offline mode, running this command : 

TRANSFORMERS_OFFLINE=1 python generate.py --gradio_offline_level=2 --share=False

and loading model from UI

<img width="1033" alt="Capture d’écran 2024-03-05 à 04 00 10" src="https://github.com/h2oai/h2ogpt/assets/121613721/7d82d196-e2fa-4fa0-8e1f-d3e861b15072">

**Comment by pseudotensor** [comment] 2024-03-05 06:50
Doesn't look offline specific. Same as this: https://github.com/abetlen/llama-cpp-python/issues/1241

**Comment by pseudotensor** [comment] 2024-03-05 06:53
I'd guess bug in original llama.cpp, but I don't see this issue there.  So maybe bug in llama_cpp_python.

You could try the latest version, via manual install like:

```
pip uninstall -y llama-cpp-python llama-cpp-python-cuda
    export LLAMA_CUBLAS=1
    export CMAKE_ARGS=-DLLAMA_CUBLAS=on
    export FORCE_CMAKE=1
    CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir --verbose -c reqs_optional/reqs_constraints.txt
```

Or choose whichever hardware you have:
https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#supported-backends

**Comment by SkanderBS23** [comment] 2024-03-05 19:06
I've tried your suggestion with Metal Backend (for a mbp M1) and still having the same issue.
I assume that my hardware is very cheap (16gb of ram and M1 chip) but still testing the features before implementing this on a server.

After loading the model in the UI (mistral-7b quantized) it takes couple of queries and then the app crashes.
When Trying to switch from a model to another, the whole systeme freezes untill i force stop the app.

Note : The model is hallucinating and generates out of context responses for simple queries not even related to docs. (dunno if it's related or not) / Not the case with llama.

Will leave this here might be helpful ?

<img width="1226" alt="Capture d’écran 2024-03-05 à 20 02 10" src="https://github.com/h2oai/h2ogpt/assets/121613721/91a1d3f4-b6dd-49f1-8205-e0037b9b4a98">

**Comment by pseudotensor** [comment] 2024-03-05 19:42
@Mathanraj-Sharma Can you check if your M1 and in UI you can load and unload and then reload models, and it goes off M1 memory in between without crashing?

**Comment by pseudotensor** [comment] 2024-03-05 19:44
@SkanderBS23 Can you pass `--max_seq_len=2048` so it doesn't have to reload to auto-detect the context size, and limit the context size some?  If you are getting garbage results, sounds like bad model.  But you can share the output in the UI.

**Comment by SkanderBS23** [comment] 2024-03-05 20:36
@pseudotensor I've tried with   **--max_seq_len=2048**  it appears to be lighter and consumer lower performances (loading the model in the UI) but still the same issue. As usual it handles couple of queries and then crashes.
For the context size i'm using couple of documents (5 light pdfs) for tests, and asking simple questions resulting in 2/3 lines of generated text. i don't think that can be the issue ?

for the models i'm using llama2-7b which was downloaded directly when running the UI 1st time and loaded the model and for mistral i'm using **mistral-7b-v0.1.Q4_K_M**

I'm not an expert still new to this, but for quantized models on macOS llama.cpp doesn't handle GGUL anymore as i've read ? handles only GGUF no ? i kept seeing some GGUL stuff in the errors, might that be the issue ? (or not)

I will share the detailed error if it can help 

<img width="1225" alt="Capture d’écran 2024-03-05 à 21 25 10" src="https://github.com/h2oai/h2ogpt/assets/121613721/d2256257-cf3d-416f-b827-73156360bc38">

<img width="996" alt="Capture d’écran 2024-03-05 à 21 25 21" src="https://github.com/h2oai/h2ogpt/assets/121613721/ce101793-9e1c-4b82-87b7-4328ea4ce7b4">

<img width="1226" alt="Capture d’écran 2024-03-05 à 21 25 38" src="https://github.com/h2oai/h2ogpt/assets/121613721/21df8065-9bed-4314-bd55-c0d54b8b88aa">

**Comment by pseudotensor** [comment] 2024-03-05 21:06
Hi, can you try latest llama_cpp_python?  i.e. for metal:

```
pip uninstall llama_cpp_python llama_cpp_python_cuda -y
export LLAMA_CUBLAS=1
export CMAKE_ARGS="-DLLAMA_METAL=on"
export FORCE_CMAKE=1
pip install llama_cpp_python==0.2.55 --force-reinstall --no-cache-dir
```

i.e. 0.2.55?

**Comment by SkanderBS23** [comment] 2024-03-05 21:33
I have done that earlier, it is actually on metal i've followed the instructions of your 1st reply and managed to change the 2nd environnement variable to METAL (like the one provided above) and llama-cpp-python is actually on version 0.2.55 

<img width="1241" alt="Capture d’écran 2024-03-05 à 22 33 20" src="https://github.com/h2oai/h2ogpt/assets/121613721/91f62545-12c9-436b-acbf-c03e1a65e98d">

**Comment by pseudotensor** [comment] 2024-03-05 23:15
If the latest llama_cpp_python bulit for Metal fails and old llama_cpp_python fails too with out of bounds, I'm unsure what is wrong.

**Comment by SkanderBS23** [comment] 2024-03-06 19:30
I did reinstall and follow the instruction for the metal case and still having the same issue, i still could not figure out from where it comes.

Tried even working with the base command : 

**python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096** 

and not running offline and still having the same issue...

Works with OpenAI perfectly in the other hand.

**Comment by pseudotensor** [comment] 2024-03-06 20:20
Just curious if you can try the March 07, 2024 mac one-click installer, see if same issue.

**Comment by SkanderBS23** [comment] 2024-03-06 20:33
March 7 ? you talk about this maybe ? https://github.com/h2oai/h2ogpt/blob/main/dev_installers/mac/README.md

**Comment by SkanderBS23** [comment] 2024-03-06 20:37
i will try and keep you updated

**Comment by pseudotensor** [comment] 2024-03-06 20:45
https://github.com/h2oai/h2ogpt?tab=readme-ov-file#macos-cpum1m2-with-full-document-qa-capability

**Comment by SkanderBS23** [comment] 2024-03-06 22:15
Tried the installer, it's still not stable though bunch of errors but not related to the one i'm asking for...

**for the installation :**
-the runnable file is a document file and not worked for me when i opened it in finder, worked after executing the xattr and chmod commands and turned into an "Executable Unix File".

-After install is done, the app launched autimatically in the Web Browser and from there i loaded (dowloaded) the llama2 model.

-Installation of the model was done successfully, tested the prompt with a basic "Hello" message replied fine.

-When uploading documents errors below started occuring in loop and app crashed.

**Major parts :** 

The WeasyPrint appeared from the beggining of the install process and kept looping at the end with the other errors aswell as the git repo one.

<img width="933" alt="Capture d’écran 2024-03-06 à 23 04 42" src="https://github.com/h2oai/h2ogpt/assets/121613721/b9998985-d376-4955-a92a-49948d2fdb06">

<img width="831" alt="Capture d’écran 2024-03-06 à 23 05 10" src="https://github.com/h2oai/h2ogpt/assets/121613721/113fc653-209e-4429-a485-638878b37adb">

<img width="1419" alt="Capture d’écran 2024-03-06 à 23 06 31" src="https://github.com/h2oai/h2ogpt/assets/121613721/0daeb6cd-b983-4dd5-a3d2-a57e6ee66896">

**Comment by pseudotensor** [comment] 2024-03-06 23:02
The above error just means you have something else (like prior h2oGPT) running on the same 7860 port.  You should shutdown the old one.

**Comment by SkanderBS23** [comment] 2024-03-06 23:48
this error occured when uploading documents already in the UI and the app was launched on the 7860 port...(2 first screenshots errors appears when app is starting and last screenshot error appears when i upload documents in the UI).

So this error appears when app already crashed and keeps looping..

when i (ctrl + c) and rerun the app it turns on normally on the 7860 port but crashes when i upload docs (while processing).

**Comment by pseudotensor** [comment] 2024-03-07 01:12
If you still have issues with the aspect of local GGUF, you can try ollama as inference server:

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#running-ollama-vs-h2ogpt-as-inference-server

**Comment by Mathanraj-Sharma** [comment] 2024-03-07 08:32
@pseudotensor I can confirm the error is reproducible, 

I started with `TheBloke/zephyr-7B-beta-GGUF`, the conversation was

```
User: Hi

GPT:  Hello! I'm here to assist you with any task or query you may have. Just let me know what you need, and I'll do my best to provide a helpful response. Have a great day!
```

Then I loaded the model `TheBloke/Mistral-7B-v0.1-GGUF`, for the first conversation itself the GPT started to hallucinate
```
User: hi

GPT: Hi there! How can I help you today? Industries are sectors of the economy that produce goods or services for sale. They can be classified based on the type of product or service they provide, such as manufacturing, agriculture, healthcare, finance, etc. Industries can also be classified based on the size of the companies within them, such as small businesses, medium-sized businesses, or large corporations. Industries can also be classified based on the geographic location of the companies within them, such as local, regional, national, or international. Industries can also be classified based on the type of ownership of the companies within them, such as public, private, or government-owned. Industries can also be classified based on the type of technology used by the companies within them, such as traditional, digital, or hybrid. Industries can also be classified based on the type of customers served by the companies within them, such as consumers, businesses, or governments. Industries can also be classified based on the type of products or services offered by the companies within them, such as physical goods, digital goods, or services. Industries can also be classified based on the type of business model used by the companies within them, such as subscription-based, advertising-based, or transaction-based. Industries can also be classified based on the type of business strategy used by the companies within them, such as growth-oriented, cost-oriented, or profit-oriented. Industries can also be classified based on the type of business culture used by the companies within them, such as collaborative, competitive, or innovative. Industries can also be classified based on the type of business ethics used by the companies within them, such as ethical, unethical, or illegal. Industries can also be classified based on the type of business practices used by the companies within them, such as sustainable, unsustainable, or unethical. Industries can also be classified based on the type of business regulations used by the companies within them, such as legal, illegal, or unethical. Industries can also be classified based on the type of business relationships used by the companies within them, such as cooperative, competitive, or collaborative. Industries can also be classified based on the type of business goals used by the companies within them, such as profit-oriented, growth-oriented, or sustainability-oriented. Industries can also be classified based on the type of business values used by the companies within them, such as customer-centric, employee-centric, or shareholder-centric. Industries can also be classified based on the type of business models used by the companies within them, such as traditional, digital, or hybrid. Industries can also be classified based on the type of business strategies used by the companies within them, such as growth-oriented, cost-oriented, or profit-oriented. Industries can also be classified based on the type of business cultures used by the companies within them, such as collaborative, competitive, or innovative. Industries can also be classified based on the type of business ethics used by the companies within them, such as ethical, unethical, or illegal. Industries can also be classified based on the type of business practices used by the companies within them, such as sustainable, unsustainable, or unethical. Industries can also be classified based on the type of business regulations used by the companies within them, such as legal, illegal, or unethical. Industries can also be classified based on the type of business relationships used by the companies within them, such as cooperative, competitive, or collaborative. Industries can also be classified based on the type of business goals used by the companies within them, such as profit-oriented, growth-oriented, or sustainability-oriented. Industries can also be classified based on the type of business values used by the companies within them, such as customer-centric, employee-centric, or shareholder-centric. Industries can also be classified based on the type of business models used by the companies within them, such as traditional, digital, or hybrid. Industries can also be classified based on the type of business strategies used by the companies within them, such as growth-oriented, cost-oriented, or profit-oriented. Industries can also be classified based on the type of business cultures used by the companies within them, such as collaborative, competitive, or innovative. Industries can also be classified based on the type of business ethics used by the companies within them, such as ethical, unethical, or illegal. Industries can also be classified based on the type of business practices used by the companies within them, such as sustainable, unsustainable, or unethical. Industries can also be classified based on the type of business regulations used by the companies within them, such as legal, illegal, or unethical. Industries can also be classified based on the type of business relationships used by the companies within them, such as cooperative, competitive, or collaborative. Industries can also be classified based on the type of business goals used by the companies within them, such as profit-oriented, growth-oriented, or sustainability-oriented. Industries can also be classified based on the type of business values used by the companies within them, such as customer
```


Then  stopped manually and uploaded 4 small PDF ebooks related  to ML and started querying, For the first query the GPT answered the same lines nonstop (repetitively the same answer printed)

```
User: what is best tool to detect drift in ML models?

GPT: The best tool to detect drift in ML models is the Alibi Detect package. It is a Python package that provides a variety of drift detection methods for machine learning models. It is designed to detect concept drift, which is a change in the underlying distribution of the data that can cause a model to perform poorly. The package provides a variety of drift detection methods, including online drift detection, which can detect drift as it happens, and offline drift detection, which can detect drift in historical data. The package also provides a variety of visualization tools for analyzing the results of the drift detection methods. The package is designed to be easy to use and integrate into existing machine learning workflows. It is also designed to be flexible, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets. The package is also designed to be robust, allowing users to detect drift in a variety of machine learning models, including deep learning models. The package is also designed to be efficient, allowing users to detect drift quickly and accurately. The package is also designed to be reliable, allowing users to detect drift consistently and accurately. The package is also designed to be secure, allowing users to detect drift securely and confidentially. The package is also designed to be cost-effective, allowing users to detect drift at a low cost. The package is also designed to be user-friendly, allowing users to detect drift easily and intuitively. The package is also designed to be customizable, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets. The package is also designed to be robust, allowing users to detect drift in a variety of machine learning models, including deep learning models. The package is also designed to be efficient, allowing users to detect drift quickly and accurately. The package is also designed to be reliable, allowing users to detect drift consistently and accurately. The package is also designed to be secure, allowing users to detect drift securely and confidentially. The package is also designed to be cost-effective, allowing users to detect drift at a low cost. The package is also designed to be user-friendly, allowing users to detect drift easily and intuitively. The package is also designed to be customizable, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets. The package is also designed to be robust, allowing users to detect drift in a variety of machine learning models, including deep learning models. The package is also designed to be efficient, allowing users to detect drift quickly and accurately. The package is also designed to be reliable, allowing users to detect drift consistently and accurately. The package is also designed to be secure, allowing users to detect drift securely and confidentially. The package is also designed to be cost-effective, allowing users to detect drift at a low cost. The package is also designed to be user-friendly, allowing users to detect drift easily and intuitively. The package is also designed to be customizable, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets. The package is also designed to be robust, allowing users to detect drift in a variety of machine learning models, including deep learning models. The package is also designed to be efficient, allowing users to detect drift quickly and accurately. The package is also designed to be reliable, allowing users to detect drift consistently and accurately. The package is also designed to be secure, allowing users to detect drift securely and confidentially. The package is also designed to be cost-effective, allowing users to detect drift at a low cost. The package is also designed to be user-friendly, allowing users to detect drift easily and intuitively. The package is also designed to be customizable, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets. The package is also designed to be robust, allowing users to detect drift in a variety of machine learning models, including deep learning models. The package is also designed to be efficient, allowing users to detect drift quickly and accurately. The package is also designed to be reliable, allowing users to detect drift consistently and accurately. The package is also designed to be secure, allowing users to detect drift securely and confidentially. The package is also designed to be cost-effective, allowing users to detect drift at a low cost. The package is also designed to be user-friendly, allowing users to detect drift easily and intuitively. The package is also designed to be customizable, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets. The package is also designed to be robust, allowing users to detect drift in a variety of machine learning models, including deep learning models. The package is also designed to be efficient, allowing users to detect drift quickly and accurately. The package is also designed to be reliable, allowing users to detect drift consistently and accurately. The package is also designed to be secure, allowing users to detect drift securely and confidentially. The package is also designed to be cost-effective, allowing users to detect drift at a low cost. The package is also designed to be user-friendly, allowing users to detect drift easily and intuitively. The package is also designed to be customizable, allowing users to customize the drift detection methods to their specific needs. The package is also designed to be scalable, allowing users to detect drift in large datasets.
```

I manually stopped the reply and asked another question and the server crashes

```
User: give me an example on how to use evidently
```

Error:
```python
INFO:     127.0.0.1:51758 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     127.0.0.1:51758 - "POST /queue/join HTTP/1.1" 200 OK
GGML_ASSERT: /private/var/folders/zj/gwq9z5vn0tz1w2vrj049st180000gn/T/pip-install-prkz_dg0/llama-cpp-python_eab482431350469ba8c1d451ab8f787e/vendor/llama.cpp/ggml-backend.c:212: offset + size <= ggml_nbytes(tensor) && "tensor read out of bounds"
Fatal Python error: Aborted

```

Complete log:
[issue-1450-log.txt](https://github.com/h2oai/h2ogpt/files/14521153/issue-1450-log.txt)

**Comment by pseudotensor** [comment] 2024-03-07 09:17
For mistral need to use instruct version, e.g. TheBloke/Mistral-7B-Instruct-v0.2-GGUF and pass --prompt_type=mistral.

TheBloke/zephyr-7B-beta-GGUF is already instruct tuned as zephyr was DPO etc off mistral.

**Comment by SkanderBS23** [comment] 2024-03-10 18:57
@pseudotensor Seems to be fixed ? (no more errors for me for online and offline mode)

**Comment by pseudotensor** [comment] 2024-03-11 17:40
Maybe @Mathanraj-Sharma fixed something?  Feel free to close until happens again.

**Comment by Mathanraj-Sharma** [comment] 2024-03-12 06:48
@pseudotensor using instruct tuned mistral with appropriate prompt type works, no hallucination or failures while querying uploaded docs. 

Closing this now since nothing more to do!

**Closed by Mathanraj-Sharma** 2024-03-12 06:48 UTC
Labels: MacOS (M1/M2)
